
<section class="cards-section text-center">
            <div class="container">
                <h2 class="title">Getting started is easy!</h2>
                <div class="intro">
                    <p>Welcome to <?php echo $name ?>. This landing page is dynamically generated by
systemx, feel free to go through the available simple tutorials to guide you in building complex applications easily. Fully customizable with powerful features.</p>
                   
                </div><!--//intro-->
                <div id="cards-wrapper" class="cards-wrapper row">
                    <div class="item item-green col-lg-4 col-6">
                        <div class="item-inner">
                            <div class="icon-holder">
                                <i class="icon fa fa-paper-plane"></i>
                            </div><!--//icon-holder-->
                            <h3 class="title">Quick Guide</h3>
                            <p class="intro">The Quick Guide has tutorials and reference documentation for the components that make up the framework. Visit the <a href>Quick Guide !</a>
							</p>
                            <a class="link" href="start.html"><span></span></a>
                        </div><!--//item-inner-->
                    </div><!--//item-->
                    <div class="item item-pink item-2 col-lg-4 col-6">
                        <div class="item-inner">
                            <div class="icon-holder">
                                <span aria-hidden="true" class="icon fa fa-puzzle-piece"></span>
                            </div><!--//icon-holder-->
                            <h3 class="title">Components</h3>
                            <p class="intro">Systemx is a community-developed open source project, feel free to join our community so as to add
create and add your favourite components <a href>Systemx forum</>!</p>
                            <a class="link" href="components.html"><span></span></a>
                        </div><!--//item-inner-->
                    </div><!--//item-->
                    
                    <div class="item item-purple col-lg-4 col-6">
                        <div class="item-inner">
                            <div class="icon-holder">
                                <span aria-hidden="true" class="icon fa fa-code"></span>
                            </div><!--//icon-holder-->
                            <h3 class="title">Contribute</h3>
                            <p class="intro">Contribute your code using github <a href>Join us now</a></p>
                            <a class="link" href="faqs.html"><span></span></a>
                        </div><!--//item-inner-->
                    </div><!--//item-->
                    
                </div><!--//cards-->
                
            </div><!--//container-->
        </section>
		</div>